import fs from 'node:fs';
import vm from 'node:vm';
const exCode=fs.readFileSync(new URL('../src/analysis/exception-groups.js', import.meta.url),'utf8');
const code = fs.readFileSync(new URL('../src/investigation/investigation.js', import.meta.url), 'utf8');
const context = { console, Date, Math, JSON, self: {} }; vm.createContext(context); vm.runInContext(exCode, context); vm.runInContext(code, context);
const api = context.self.SignalDockInvestigation;
let notebook = api.empty();
const entry = { id:'sd-4', globalIndex:4, source:'api.log', service:'auth', level:'ERROR', timestamp:'2026-09-12T10:00:00.000Z', message:'TimeoutError: token 123 expired', raw:{exception:{type:'TimeoutError'}}, correlations:{trace:'t1'}, traceMeta:{durationMs:12}, dimensions:{environment:'prod'} };
let result = api.add(notebook, entry, 'Investigate this', ['Auth', 'incident 42']); notebook = result.notebook;
if (!result.added || notebook.items.length !== 1) throw new Error('evidence add failed');
if (!notebook.items[0].snapshot?.correlations?.trace || !notebook.items[0].fingerprint) throw new Error('self-contained evidence snapshot failed');
result = api.add(notebook, entry); if (result.added || result.notebook.items.length !== 1) throw new Error('duplicate guard failed');
notebook = api.update(notebook, notebook.items[0].id, { note:'Updated', tags:'security, auth' });
if (notebook.items[0].note !== 'Updated' || !notebook.items[0].tags.includes('security')) throw new Error('update failed');
const md = api.exportMarkdown(notebook); if (!md.includes('token 123 expired') || !md.includes('Updated') || !md.includes('ex-')) throw new Error('markdown export failed');
const round = api.importJson(api.exportJson(notebook)); if (round.items.length !== 1 || round.version !== 2) throw new Error('json roundtrip failed');
let badInvestigationVersion=false;try{api.importJson(JSON.stringify({schema:'signaldock.investigation',version:'2',items:[]}))}catch{badInvestigationVersion=true}if(!badInvestigationVersion)throw new Error('string investigation version must be rejected');
const legacy = api.importJson(JSON.stringify({schema:'signaldock.investigation',version:1,title:'Legacy',items:[{id:'x',message:'old'}]})); if(legacy.items.length!==1||legacy.version!==2)throw new Error('legacy migration failed');
let badBundleVersion=false;try{api.importBundle(JSON.stringify({schema:'signaldock.evidence-bundle',version:'2',investigation:{schema:'signaldock.investigation',version:2,items:[]}}))}catch{badBundleVersion=true}if(!badBundleVersion)throw new Error('string evidence bundle version must be rejected');
const bundleText=api.exportBundle(notebook,{appVersion:'2.0.0',sourceLabel:'test',caseFile:{schema:'signaldock.case',version:1,title:'Incident',status:'investigating',severity:'sev2',findings:[]}}); const bundle=api.importBundle(bundleText); if(bundle.investigation.items[0].snapshot?.dimensions?.environment!=='prod')throw new Error('evidence bundle roundtrip failed'); if(bundle.caseFile?.severity!=='sev2')throw new Error('case workspace missing from evidence bundle');
const timeline=api.timeline(notebook); if(!timeline.buckets.length||timeline.total!==1)throw new Error('timeline failed');
notebook = api.remove(round, round.items[0].id); if (notebook.items.length) throw new Error('remove failed');
console.log('investigation smoke ok');
